name: 'Broken Method'
description: 'This method no longer works and needs updating.'
title: '[BROKEN]: '
labels: ['broken :adhesive_bandage:']
assignees: []
body:
  - type: markdown
    attributes:
      value: '## Broken Method Report'
  - type: markdown
    attributes:
      value: |
        This is a report to tell us that this method for Vercel no longer works.
  - type: input
    id: error
    attributes:
      label: Vercel Error
      description: 'What error does Vercel tell you?'
    validations:
      required: false
