name: '🩹 Broken Method'
description: 'This method no longer works and needs to be updated.'
title: '[BROKEN]: '
labels: ['Broken Method', 'Unsolved']
assignees: ['QVGK']
body:

  - type: input
    id: when
    attributes:
      label: When did this start to occur?
    validations:
      required: true
      
  - type: dropdown
    id: status
    attributes:
      label: Are any Vercel APIs down?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
    
    
  - type: input
    id: error
    attributes:
      label: What error does Vercel give you?
      description: 'Not required if you do not know.'
    validations:
      required: false
