---
name: 'Broken Method'
title: '[BROKEN]'
about: 'This method no longer works and needs to be updated.'
labels: 'broken :adhesive_bandage:'
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

---


