name: 'Broken Method'
description: 'This method no longer works and needs updating.'
title: '[BROKEN]: '
labels: ['broken :adhesive_bandage:']
assignees: []
body:

  - type: input
    id: when
    attributes:
      label: When did this start to occur?
      description: 'What error does Vercel give you?'
    validations:
      required: true
      
  - type: dropdown
    id: status
    attributes:
      label: Are any Vercel APIs down?
      description: 'https://status.vercel.com'
    validations:
      required: true
    
    
  - type: input
    id: error
    attributes:
      label: Vercel Error
      description: 'What error does Vercel give you?'
    validations:
      required: true
