name: '📖 Documentation Update'
description: 'The README documentation is incorrect or has a typo that needs to be fixed.'
title: '[DOCUMENTATION]: '
assignees: ['QVGK']
labels: ['Invalid Documentation', 'Unsolved']

body:
   
  - type: dropdown
    id: status
    attributes:
      label: Is there incorrect information or an error that needs to be updated?
      options:
        - 'Incorrect Information'
        - 'Error'
        - 'Other'
    validations:
      required: true
    
    
  - type: textarea
    id: fixing
    attributes:
      label: What needs to be updated?
    validations:
      required: true
